### ISSUE TITLE
International rates

### ISSUE THREAD

**Issue by imjustd** [uh-opensource/node-shipping-usps#3]
Hi, not really an issue, I was just wondering if the module can calculate international shipping rates as I didn't noticed such function? If there aren't interantional rates estimaton, can it be easily implemented with the current code.

**Edit:** I implemented the international shipping rates, but I can't merge the code with yours. I can't push to the repo and create pull request.

**Comment by jjosef** [comment]
You will need to fork the repo first (I do not see your fork listed) and then submit a pull request from your fork.

Thanks for your efforts! Look forward to seeing what you've done.
